# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CGF_c <- function(info, t) {
    .Call('_dicosar_CGF_c', PACKAGE = 'dicosar', info, t)
}

del_CGF_c <- function(info, t) {
    .Call('_dicosar_del_CGF_c', PACKAGE = 'dicosar', info, t)
}

g_c <- function(z) {
    .Call('_dicosar_g_c', PACKAGE = 'dicosar', z)
}

del_g_c <- function(z) {
    .Call('_dicosar_del_g_c', PACKAGE = 'dicosar', z)
}

seq_c <- function(info1, info2, t, zeta) {
    .Call('_dicosar_seq_c', PACKAGE = 'dicosar', info1, info2, t, zeta)
}

